### ISSUE TITLE
Feature: BOOKMARK

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/CRYPTAWARE-FULLSTACK-TS#28]
> Logged User will be able to bookmark search results and have them easily accessible via the buttons in Options Elements.

> Furthermore, This bookmark list will be used to render the bookmark option which renders as a modal for managing it in one dedicated spot.

## This entire segment will take place in the Selection Element and ticker ctx (with some Auth involvement)
- [x] Add to ticker context the function to add and remove from list
- [x] Fix ticker type and no longer render hard coded data
- [x] Ensure to review typing  to accept empty arrays
- [x] Maintain BTC as the default data presented by the browser in case list is empty (from server)
- [x] Ensure bookmark icon toggles and changes, appropriately reflecting actions 

## In a rough manner, ensure bookmark modal map the items

- [ ] Prepare Bookmark section to receive the data
- [ ] Leave a rough map to be used with structured
- [ ] No style needed
- [x] RESTRUCTURE MVP: Remove bookmark modal as comment for future

## Send requests to server in order to persist in DB

- [x] Refactor onBookmark function to do what it does after a 2xx from the server
- [x] Create a route to update list in DB
- [x] Verify Token before allowing any CRUD operation
- [x] Add element to the list in DB
- [x] Ensure UI responds as expected with data being received from the server
- [x] Refactor removeBookmark function to do what it does after a 2xx from the server
- [x] Refactor onBookmark function to do what it does after a 2xx from the server
- [x] Create a route to update list in DB
- [x] Add to the list in DB
- [x] Create a route to update list in DB
- [x] Remove item from the list in DB
- [x] Structure API into proper directories

Accomplishing these tasks will complete the functionality of the feature, allow for future proper structure of Bookmark Component
