### ISSUE TITLE
Extra TSX structure to be used in Full-Stack

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/CRYPTAWARE-FULLSTACK-TS#4]
> In the full stack version, extra features are added which will require additional structure/components

- [x] Bookmark/Favorite icon on Select component
- [x] Header extra components: All rendered within portal, conditionally on MODAL. Notes component (crud), Bookmark List component(crud), logout.
- [x] Header conditional: Not auth (no search input, h1 only), Auth (search, plus bookmark list, plus notes, plus logout)
