### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/CRYPTAWARE-FULLSTACK-TS#9]
> CLIENT-SIDE:

- [x] Create Login component 
- [x] Create Register component
- [x] Bind inputs
- [x] Will take username and password
- [x] Once logged in or registered, will be auth to use app
- [x] Token received from server will be stored in local storage
- [x] Expiration date on Token will be matched in local Storage
- [x] Effect will run to check if token is not expired

> SERVER-SIDE

- [x] Create Schema for user
- [x] Create Register route (encryption of password)
- [x] Generate Token
- [x] Send Pertinent User data along with Token to Client
- [x] Create Login route (decryption of password
- [x] Generate Token
- [x] Send Pertinent User data along with Token to Client
